### ISSUE TITLE
Network Down

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/network#11]
I am getting the following error 

```
2018-05-25 21:43:04 E/MessageCenterService: connection error
2018-05-25 21:43:04 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'beta.kontalk.net:5222 prio:5:w:0' failed because: /46.101.92.252 exception: java.net.SocketTimeoutException: failed to connect to /46.101.92.252 (port 5222) from /192.168.178.21 (port 40252) after 30000ms, 'beta.kontalk.net:5222' failed because: /46.101.92.252 exception: java.net.SocketTimeoutException: failed to connect to /46.101.92.252 (port 5222) from /192.168.178.21 (port 40256) after 30000ms
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:205)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:264)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:147)
```

Is the network down?

**Comment by daniele-athome** [comment]
There was an issue with our log analysis tool. Fixed, thanks for reporting.
